version: "3"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"

  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: admin-pw
      POSTGRES_DB: paperless
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "paperless" ]
      interval: 10s
      timeout: 5s
      retries: 20

  elasticsearch:
    image: elasticsearch:7.17.7
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"

#  elastic_search:
#    image: elasticsearch:8.7.1
#    environment:
#      - discovery.type=single-node
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "xpack.security.enabled=false"
#      - "xpack.security.enrollment.enabled=false"
#    # ulimits:
#    #   memlock:
#    #     soft: -1
#    #     hard: -1
#    portsa:
#      - 9200:9200
#      - 9300:9300
#  kibanba:
#    image: docker.elastic.co/kibana/kibana:8.2.3
#    ports:
#      - 5601:5601

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin-pw
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"

volumes:
  postgres_data:
  minio_data:
